#!/bin/bash
# Ubuntu/Debian
# https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/download-cloudwatch-agent-commandline.html


export REGION=us-east-1
export APPLICATION_LOGS=/opt/myapp.log
export LOG_GROUP_NAME=myapp-asim
export LOG_STREAM_NAME=myapp-asim-stream

############################
# Cloudwatch Ubuntu Package
############################
curl -LO -# https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb

sudo dpkg -i -E ./amazon-cloudwatch-agent.deb



# CloudWatch Agent Configuration

cat <<EOF > /opt/aws/amazon-cloudwatch-agent/bin/config.json
{
     "agent": {
         "run_as_user": "root"
     },
     "logs": {
         "logs_collected": {
             "files": {
                 "collect_list": [
                     {
                         "file_path": "${APPLICATION_LOGS}",
                         "log_group_name": "${LOG_GROUP_NAME}",
                         "log_stream_name": "${LOG_STREAM_NAME}"
                     }
                 ]
             }
         }
     }


 }

EOF

# Command to Start CloudWatch Service
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json -s
