#!/bin/bash
# https://github.com/terraform-linters/tflint
# https://github.com/terraform-linters/tflint


cat << EOF > .tflint.hcl
plugin "aws" {
    enabled = true
    version = "0.12.0"
    source  = "github.com/terraform-linters/tflint-ruleset-aws"
}

EOF

# End

# tflint --help

# tflinit --init

# tflinit  # this will validate your terraform code
